/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.starter

import org.amshove.kluent.`should equal`
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun `it should greet user`() {
        App().greeting `should equal` "Hello World!"
    }
}